<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <UserSecretsId>dotnet-CmsApi.Worker-215adb64-ecac-4904-b214-9cfc735f4d6e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CmsApi.Core\CmsApi.Core.csproj" />
    <ProjectReference Include="..\CmsApi.Data\CmsApi.Data.csproj" />
  </ItemGroup>
</Project>
