// <auto-generated />
using System;
using CmsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CmsApi.Data.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260929190143_AddContentEntitiesAndEventLog")]
    partial class AddContentEntitiesAndEventLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CmsApi.Data.ContentEntities.ContentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisabledBy")
                        .HasColumnType("text")
                        .HasColumnName("disabled_by");

                    b.Property<bool>("IsDisabledByAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled_by_admin");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTimeOffset>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_content_entities");

                    b.HasIndex(new[] { "LastEventAt", "Id" }, "ix_content_entities_last_event_at_id")
                        .IsDescending(true, false)
                        .HasDatabaseName("ix_content_entities_last_event_at_id");

                    b.HasIndex(new[] { "LastEventAt", "Id" }, "ix_content_entities_visible_last_event_at_id")
                        .IsDescending(true, false)
                        .HasDatabaseName("ix_content_entities_visible_last_event_at_id")
                        .HasFilter("is_published AND NOT is_disabled_by_admin");

                    b.ToTable("content_entities", (string)null);
                });

            modelBuilder.Entity("CmsApi.Data.EventLog.EventLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<string>("ContentEntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<DateTimeOffset?>("EventTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawEvent")
                        .HasColumnType("text")
                        .HasColumnName("raw_event");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long?>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_event_log");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_event_log_batch_id");

                    b.HasIndex("ContentEntityId", "Id")
                        .HasDatabaseName("ix_event_log_entity_id_id");

                    b.ToTable("event_log", (string)null);
                });

            modelBuilder.Entity("CmsApi.Data.Inbox.InboxBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_inbox");

                    b.HasIndex("NextAttemptAt", "Id")
                        .HasDatabaseName("ix_inbox_next_attempt_at_id")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("CmsApi.Data.EventLog.EventLogEntry", b =>
                {
                    b.HasOne("CmsApi.Data.Inbox.InboxBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_log_inbox_batches_batch_id");
                });
#pragma warning restore 612, 618
        }
    }
}
