// <auto-generated />
using System;
using CmsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CmsApi.Data.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260929201126_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CmsApi.Data.ContentEntities.ContentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisabledBy")
                        .HasColumnType("text")
                        .HasColumnName("disabled_by");

                    b.Property<bool>("IsDisabledByAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled_by_admin");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTimeOffset>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_content_entities");

                    b.HasIndex(new[] { "LastEventAt", "Id" }, "ix_content_entities_last_event_at_id")
                        .IsDescending(true, false)
                        .HasDatabaseName("ix_content_entities_last_event_at_id");

                    b.HasIndex(new[] { "LastEventAt", "Id" }, "ix_content_entities_visible_last_event_at_id")
                        .IsDescending(true, false)
                        .HasDatabaseName("ix_content_entities_visible_last_event_at_id")
                        .HasFilter("is_published AND NOT is_disabled_by_admin");

                    b.ToTable("content_entities", (string)null);
                });

            modelBuilder.Entity("CmsApi.Data.EventLog.EventLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<string>("ContentEntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<DateTimeOffset?>("EventTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_timestamp");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RawEvent")
                        .HasColumnType("text")
                        .HasColumnName("raw_event");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long?>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_event_log");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_event_log_batch_id");

                    b.HasIndex("ContentEntityId", "Id")
                        .HasDatabaseName("ix_event_log_entity_id_id");

                    b.ToTable("event_log", (string)null);
                });

            modelBuilder.Entity("CmsApi.Data.Inbox.InboxBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer")
                        .HasColumnName("event_count");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_inbox");

                    b.HasIndex("NextAttemptAt", "Id")
                        .HasDatabaseName("ix_inbox_next_attempt_at_id")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("CmsApi.Data.Tombstones.Tombstone", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id")
                        .HasName("pk_tombstones");

                    b.ToTable("tombstones", (string)null);
                });

            modelBuilder.Entity("CmsApi.Data.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b1f0c9e-2d4a-4e7b-8c3f-1a6d9e2b7c40"),
                            PasswordHash = "$argon2id$v=19$m=19456,t=2,p=1$OLXIgDfhEDkEgUiWOhjZ+A$WlaQcUtsEyNRPgpTN0Zaf6DOtE8P+KFOGwR9CHU6smA",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("8e3a6d21-7c5b-4f90-a1e4-3d2c8b6f5a19"),
                            PasswordHash = "$argon2id$v=19$m=19456,t=2,p=1$SKxVoHRqiIBsIR2YouAfdA$C5+Yz6MqMxWWNi7Vu7Ay6YUn+lMf3vSbD5TBkZwGkk0",
                            Role = "User",
                            Username = "reader"
                        });
                });

            modelBuilder.Entity("CmsApi.Data.EventLog.EventLogEntry", b =>
                {
                    b.HasOne("CmsApi.Data.Inbox.InboxBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_log_inbox_batches_batch_id");
                });
#pragma warning restore 612, 618
        }
    }
}
