<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\CmsApi.Core\CmsApi.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageReference
      Include="Microsoft.Extensions.Options.ConfigurationExtensions"
      Version="10.0.12"
    />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
  </ItemGroup>
</Project>
